version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Це дозволяє зберігати дані на хості
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Зберігання даних MongoDB за межами контейнера

volumes:
  mongo-data:
